### ISSUE TITLE
Does not work with ^steal@0.15.9

### ISSUE THREAD

**Issue by m-mujica** [stealjs/react-example#3]
There was a change in steal@0.15.9 that breaks this example:

(I did some debugging and `moduleName` is an array instead of a string)

<img width="1188" alt="screen shot 2016-04-17 at 13 59 37" src="https://cloud.githubusercontent.com/assets/724877/14588689/5ed028bc-04a5-11e6-9569-e97cedc16f0c.png">

It works fine in steal@0.15.8

**Comment by QuantumInformation** [comment]
same error with 0.15.10

![image](https://cloud.githubusercontent.com/assets/216566/15042701/2f1befa8-12be-11e6-9f0b-e8e9bf93fa0c.png)

**Comment by Xitstrategies** [comment]
Just a heads up, it works with 0.16.4

**Comment by matthewp** [comment]
If someone wants to update this example to steal 0.16 we can close this.

**Comment by Xitstrategies** [comment]
I updated it in my new pull request.

**Comment by matthewp** [comment]
Thanks!
