### ISSUE TITLE
Confusion regarding how to run

### ISSUE THREAD

**Issue by capouch** [stealjs/react-example#6]
I cloned the repo and then did "npm install"

There doesn't seem to be any server code, but when I try to run it by loading index.html as a file, I get only a number of errors.  Console output from the Developer's Tools is below.

*\* snip **
steal.js:2648 XMLHttpRequest cannot load file:///home/brianc/PROJECTS/react-example/node_modules/steal/ext/npm.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.fetchTextFromURL @ steal.js:2648
steal.js:6222 steal - error loading @config. Error loading "package.json!npm" at <unknown>
Error loading "npm" at file:///home/brianc/PROJECTS/react-example/node_modules/steal/ext/npm.js
: file:///home/brianc/PROJECTS/react-example/node_modules/steal/ext/npm.js
steal.js:2648 XMLHttpRequest cannot load file:///home/brianc/PROJECTS/react-example/node_modules/steal/ext/dev.js. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.fetchTextFromURL @ steal.js:2648
steal.js:6395 Error loading "@dev" at file:///home/brianc/PROJECTS/react-example/node_modules/steal/ext/dev.js
: file:///home/brianc/PROJECTS/react-example/node_modules/steal/ext/dev.js undefined

**Comment by marshallswain** [comment]
I think this is related to a common issue with how Chrome handles file urls.  Can you try opening this by starting a server in the root directory, instead.  Something like

```
npm install http-server -g
http-server
```
Then open [http://localhost:8080](http://localhost:8080)

**Comment by capouch** [comment]
Yah, that's what I did, but I assumed that a skeletal demo server would be around in the sources somewhere.  I don't think Chrome is the only browser that forbids it.

**Comment by marshallswain** [comment]
Yeah.  We should either add one or update the README.md to reflect what really needs to be done.

**Comment by matthewp** [comment]
Closed by https://github.com/stealjs/react-example/pull/8
