### ISSUE TITLE
describe how to create a production version of this example

### ISSUE THREAD

**Issue by reinaldoarrosi** [stealjs/react-example#9]
This issue is the result of discussion in https://github.com/stealjs/steal-tools/issues/630
The problem is that, even when setting NODE_ENV=production, steal-tools does not produce a correct bundle when using react, which causes some warnings to be shown.

A possible workaround is described here https://github.com/stealjs/steal-tools/issues/630#issuecomment-286522571

Another possible solution (the one I ended up using) is configuring steal-tools to use a custom minify function, which uses loose-envify and uglify-js to replace process.env.NODE_ENV and remove dead code.

**Comment by m-mujica** [comment]
I wonder if we should close this one given that `envify` is now on by default. @matthewp

**Comment by matthewp** [comment]
Yeah, good point
